name: Get GitLab Group Members

on:
  workflow_dispatch:

jobs:
  get_group_members:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script to get GitLab group members
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        python script_name.py

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: gitlab-group-members
        path: list_gitlab_group_ids_and_members.csv
